# GDP Per Capita Analysis

GDP per capita data was taken from world bank
https://data.worldbank.org/indicator/NY.GDP.PCAP.CD

In [1]:
import pandas as pd

read "gdp_per_capita.csv" file into a dataframe

In [4]:
data=pd.read_csv("gdp_per_capita_2020July.csv",skiprows=4)

In [5]:
type(data)

pandas.core.frame.DataFrame

check the top-five rows the data frame

In [6]:
data.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Unnamed: 64
0,Aruba,ABW,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,24985.993281,24713.698045,26189.435509,26647.938101,27980.880695,28281.350482,29007.693003,NaN,NaN,NaN
1,Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,59.773194,59.860874,58.458015,78.706388,82.095231,101.108305,...,591.162759,641.871479,637.165523,613.856689,578.466353,547.228110,556.302002,524.162881,502.115487,NaN
2,Angola,AGO,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,4615.468028,5100.095808,5254.882338,5408.410496,4166.979684,3506.072885,4095.812942,3289.646664,2973.591160,NaN
3,Albania,ALB,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,4437.142885,4247.629984,4413.060861,4578.631994,3952.801215,4124.055726,4531.020806,5284.380184,5352.857411,NaN
4,Andorra,AND,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,43335.328862,38686.461264,39538.766722,41303.929371,35762.523074,37474.665406,38962.880354,41793.055258,40886.391165,NaN

In [8]:
#set index of the dataframe as Country name
data.set_index("Country Name")

,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Unnamed: 64
Country Name,,,,,,,,,,,,,,,,,,,,,
Aruba,ABW,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24985.993281,24713.698045,26189.435509,26647.938101,27980.880695,28281.350482,29007.693003,NaN,NaN,NaN
Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,59.773194,59.860874,58.458015,78.706388,82.095231,101.108305,137.594352,...,591.162759,641.871479,637.165523,613.856689,578.466353,547.228110,556.302002,524.162881,502.115487,NaN
Angola,AGO,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4615.468028,5100.095808,5254.882338,5408.410496,4166.979684,3506.072885,4095.812942,3289.646664,2973.591160,NaN
Albania,ALB,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4437.142885,4247.629984,4413.060861,4578.631994,3952.801215,4124.055726,4531.020806,5284.380184,5352.857411,NaN
Andorra,AND,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,43335.328862,38686.461264,39538.766722,41303.929371,35762.523074,37474.665406,38962.880354,41793.055258,40886.391165,NaN
Arab World,ARB,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6867.692047,7465.151651,7519.808260,7457.461109,6387.660615,6097.239025,6102.211067,6603.351190,6580.056257,NaN
United Arab Emirates,ARE,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,39194.676621,40976.499711,42412.630278,43751.838886,38663.383807,38141.846759,40644.804043,43839.356349,43103.323058,NaN
Argentina,ARG,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,1155.890170,850.304737,1173.238213,1279.113432,1272.802978,...,12848.864197,13082.664326,13080.254732,12334.798245,13789.060425,12790.242473,14591.863381,11683.949622,10006.148974,NaN
Armenia,ARM,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3525.804747,3681.857456,3838.185801,3986.231624,3607.296697,3591.829276,3914.501268,4220.490277,4622.733493,NaN
American Samoa,ASM,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10294.302265,11568.793001,11505.393714,11507.232349,11843.331183,11696.955562,10823.444804,11466.690706,NaN,NaN
Antigua and Barbuda,ATG,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12746.205024,13272.441329,12909.744178,13501.580922,14286.093160,15197.617455,15383.415188,16726.980808,17790.309307,NaN
Australia,AUS,GDP per capita (current US$),NY.GDP.PCAP.CD,1807.785710,1874.732106,1851.841851,1964.150470,2128.068355,2277.558398,2340.438685,...,62517.833747,68012.147901,68150.107041,62510.791171,56755.721712,49971.131456,54066.471269,57395.919466,54907.101910,NaN
Austria,AUT,GDP per capita (current US$),NY.GDP.PCAP.CD,935.460427,1031.815004,1087.834243,1167.000532,1269.412583,1374.532140,1486.968606,...,51374.958407,48567.695286,50716.708706,51717.495941,44178.047378,45237.805092,47549.079040,51525.046434,50277.275087,NaN
Azerbaijan,AZE,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7189.691229,7496.294648,7875.756953,7891.313147,5500.310382,3880.738731,4147.089716,4739.841710,4793.587020,NaN
Burundi,BDI,GDP per capita (current US$),NY.GDP.PCAP.CD,70.051735,71.167188,73.435306,78.514329,86.161606,51.381865,52.182650,...,249.577979,252.358980,256.976003,274.857948,305.549773,282.193130,292.997631,271.752044,261.247473,NaN
Belgium,BEL,GDP per capita (current US$),NY.GDP.PCAP.CD,1273.691659,1350.197673,1438.523233,1535.023729,1701.846276,1835.594766,1957.626080,...,47348.525020,44673.115876,46744.662544,47700.540360,40991.808138,41998.335750,44288.508040,47491.323259,46116.699234,NaN
Benin,BEN,GDP per capita (current US$),NY.GDP.PCAP.CD,93.022509,95.572155,94.464535,99.859114,104.339768,110.132794,112.940836,...,1130.273132,1145.140811,1251.210518,1291.409808,1076.797716,1087.287832,1136.592847,1240.829464,1219.432672,NaN
Burkina Faso,BFA,GDP per capita (current US$),NY.GDP.PCAP.CD,68.424749,71.558180,76.520611,78.372072,80.472767,81.725115,82.545637,...,751.172957,758.000701,787.470176,792.846778,653.326980,687.670175,738.274159,820.160794,774.839690,NaN
Bangladesh,BGD,GDP per capita (current US$),NY.GDP.PCAP.CD,89.035241,97.595274,100.122116,101.901414,100.221114,106.646648,112.665359,...,861.758444,883.105001,981.839879,1118.853663,1248.453398,1401.620466,1563.913857,1698.350394,1855.739824,NaN
Bulgaria,BGR,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7806.348652,7393.189177,7651.817881,7874.260904,7053.603706,7545.790332,8331.058025,9423.558612,9737.601351,NaN
Bahrain,BHR,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,22514.237946,23654.351391,24744.296959,24989.400120,22688.944400,22619.116672,23709.430468,23991.056677,23503.977127,NaN
"Bahamas, The",BHS,GDP per capita (current US$),NY.GDP.PCAP.CD,1550.239392,1651.288985,1752.854481,1867.025012,1994.380832,2144.754403,2322.689948,...,28006.379718,29485.620929,28768.029894,29445.030529,31405.963560,31588.834999,31827.242699,32217.871590,32933.486015,NaN
Bosnia and Herzegovina,BIH,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5092.551943,4778.636088,5131.394506,5329.635045,4727.277546,4994.683140,5394.591220,6072.180992,6073.265203,NaN
Belarus,BLR,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6519.230195,6940.159254,7978.872615,8318.512690,5949.106307,5022.626643,5761.747120,6330.075246,6663.295293,NaN
Belize,BLZ,GDP per capita (current US$),NY.GDP.PCAP.CD,304.917107,316.403606,327.126867,336.941466,351.161126,377.594305,406.097967,...,4423.489797,4505.621302,4568.502958,4705.602690,4775.955648,4818.403909,4887.577208,4884.734162,4815.163711,NaN
Bermuda,BMU,GDP per capita (current US$),NY.GDP.PCAP.CD,1902.402119,1961.538169,2020.385965,2020.265248,2199.727007,2282.216546,2630.850466,...,85973.158416,85458.455508,85748.065414,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bolivia,BOL,GDP per capita (current US$),NY.GDP.PCAP.CD,102.237890,109.061012,116.925153,123.429310,136.312431,149.640074,162.326054,...,2346.337170,2609.880819,2908.200085,3081.878834,3035.972215,3076.658949,3351.124040,3548.590153,3552.068762,NaN
Brazil,BRA,GDP per capita (current US$),NY.GDP.PCAP.CD,210.109899,205.040768,260.425653,292.252136,261.666620,261.354355,315.797203,...,13245.612500,12370.024201,12300.324882,12112.588206,8814.000987,8710.096690,9925.386238,9001.234249,8717.186278,NaN
Barbados,BRB,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16458.353211,16249.559394,16451.163576,16489.072237,16525.073250,16900.166552,17391.425866,17745.193465,18148.244926,NaN
Brunei Darussalam,BRN,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,1113.826555,1237.563579,...,47055.841117,47740.514902,44740.085019,41726.783972,31164.562029,27157.823410,28572.146778,31628.328791,31086.751079,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Latin America & the Caribbean (IDA & IBRD countries),TLA,GDP per capita (current US$),NY.GDP.PCAP.CD,365.695285,376.089531,418.736837,410.037568,444.760748,460.881603,492.153522,...,10128.632241,10111.758072,10247.214019,10334.430668,8728.070160,8417.027467,9288.199577,8924.133351,8681.196686,NaN
Timor-Leste,TLS,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,947.513730,1013.050451,1210.033296,1232.456832,1334.661956,1358.201692,1294.715534,1237.102682,1294.188934,NaN
Middle East & North Africa (IDA & IBRD countries),TMN,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4644.130504,5036.720832,4623.479680,4483.061040,3955.555060,3938.533311,3799.787291,NaN,NaN,NaN
Tonga,TON,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4084.624132,4597.742305,4428.566481,4393.940811,4320.637990,3966.156520,4217.476507,4364.015561,NaN,NaN
South Asia (IDA & IBRD),TSA,GDP per capita (current US$),NY.GDP.PCAP.CD,82.347834,86.048624,89.913986,98.981502,110.877920,116.487941,95.802378,...,1367.313138,1364.416403,1381.856627,1494.420765,1541.803686,1651.089463,1866.886067,1899.609233,1959.917165,NaN
Sub-Saharan Africa (IDA & IBRD countries),TSS,GDP per capita (current US$),NY.GDP.PCAP.CD,131.710996,133.716643,141.494765,158.268493,150.876008,163.955336,172.603810,...,1745.443057,1781.433136,1849.693610,1885.472563,1673.449291,1504.238409,1560.887347,1589.425156,1585.436468,NaN
Trinidad and Tobago,TTO,GDP per capita (current US$),NY.GDP.PCAP.CD,631.702115,676.398050,704.219154,760.401295,788.702764,807.874268,787.339263,...,19034.149197,19157.417037,20143.664449,20270.859372,18289.704340,16176.947370,16238.193192,17129.913090,17276.465447,NaN
Tunisia,TUN,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,217.911274,224.294846,...,4264.674946,4152.678587,4222.703245,4305.474165,3861.688531,3697.930831,3481.228739,3438.789089,3317.541013,NaN
Turkey,TUR,GDP per capita (current US$),NY.GDP.PCAP.CD,509.423852,283.828274,309.446667,350.662950,369.583432,386.358086,444.549441,...,11335.510510,11707.259712,12519.391426,12095.854572,10948.724607,10820.633842,10513.648432,9370.176355,9042.492983,NaN
Tuvalu,TUV,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3640.723240,3507.940655,3454.828692,3398.706483,3197.772252,3255.928693,3572.493579,3700.744263,4059.029996,NaN
Tanzania,TZA,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,781.437014,867.867681,970.416938,1030.092917,947.933446,966.474622,1004.841121,1060.994615,1122.121810,NaN
Uganda,UGA,GDP per capita (current US$),NY.GDP.PCAP.CD,62.509598,63.221022,62.226340,69.173562,76.311526,110.802233,112.032086,...,825.838435,783.717921,803.509374,876.354300,840.401571,730.625040,747.196907,767.097760,776.768576,NaN
Ukraine,UKR,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3569.758121,3855.417729,4029.711252,3104.643206,2124.662319,2187.730510,2640.675677,3096.817402,3659.031312,NaN
Upper middle income,UMC,GDP per capita (current US$),NY.GDP.PCAP.CD,181.614129,164.640081,170.678748,174.105284,192.377586,208.545408,223.700323,...,7225.172229,7678.096345,8070.062903,8258.437751,7695.503939,7629.406856,8364.770425,8911.911519,9040.045782,NaN
Uruguay,URY,GDP per capita (current US$),NY.GDP.PCAP.CD,489.351689,601.703237,656.713479,584.291412,741.243607,701.704979,664.438865,...,14236.681189,15171.584663,16973.674213,16831.972944,15613.764273,15387.144030,17322.147389,17277.970110,16190.126957,NaN
United States,USA,GDP per capita (current US$),NY.GDP.PCAP.CD,3007.123445,3066.562869,3243.843078,3374.515171,3573.941185,3827.527110,4146.316646,...,49886.818109,51610.605278,53117.667831,55047.725560,56822.518820,57927.516852,59957.725851,62996.664816,65280.682241,NaN
Uzbekistan,UZB,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1926.292997,2137.025122,2281.410973,2492.336643,2615.025134,2567.799207,1826.566919,1529.082864,1724.841134,NaN
St. Vincent and the Grenadines,VCT,GDP per capita (current US$),NY.GDP.PCAP.CD,161.361347,170.379137,174.500270,162.809320,173.399565,175.654363,185.262486,...,6242.195332,6390.310632,6639.607146,6684.807367,6920.878074,7075.065820,7212.960181,7361.400962,7463.537831,NaN
"Venezuela, RB",VEN,GDP per capita (current US$),NY.GDP.PCAP.CD,955.446183,970.356398,1023.355588,1077.402694,864.471682,869.535292,876.153926,...,10955.349913,12985.505325,12456.712454,16054.490513,NaN,NaN,NaN,NaN,NaN,NaN
British Virgin Islands,VGB,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Virgin Islands (U.S.),VIR,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,39144.165774,37849.728721,34819.147755,33573.097030,34797.140470,35931.541252,35938.024388,NaN,NaN,NaN
Vietnam,VNM,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1525.115988,1735.141276,1886.671896,2030.261955,2085.101484,2192.214539,2365.621666,2566.596950,2715.276036,NaN
Vanuatu,VUT,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3264.537017,3133.090209,3124.233078,3088.258303,2801.939848,2889.853036,3082.356323,3095.702156,3058.065675,NaN
World,WLD,GDP per capita (current US$),NY.GDP.PCAP.CD,452.108859,464.049009,489.547101,516.615106,554.553301,591.718115,628.738759,...,10488.334016,10605.208322,10781.855305,10952.344419,10246.507362,10281.908800,10817.481947,11381.680597,11435.609873,NaN
Samoa,WSM,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3933.459357,4022.199120,4037.509315,3937.758712,4073.666010,4109.165135,4258.486270,4183.408032,4315.920675,NaN
Kosovo,XKX,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3741.875052,3596.804655,3891.266363,4080.330717,3603.025501,3780.003689,4045.614209,4419.914327,4417.509940,NaN
"Yemen, Rep.",YEM,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1374.621285,1446.536354,1607.152365,1673.146354,1395.439633,1033.733043,882.395759,968.159048,NaN,NaN
South Africa,ZAF,GDP per capita (current US$),NY.GDP.PCAP.CD,443.009816,454.962013,473.011615,511.497253,548.995942,584.704072,621.220825,...,8007.412846,7501.469984,6832.456891,6433.187277,5734.633629,5272.918425,6132.479841,6374.028196,6001.400814,NaN
Zambia,ZMB,GDP per capita (current US$),NY.GDP.PCAP.CD,232.188867,220.042137,212.578123,213.896441,242.384333,303.281910,343.373483,...,1672.908251,1763.072733,1878.907001,1763.057298,1337.796110,1280.578898,1534.865371,1556.334482,1291.343357,NaN
Zimbabwe,ZWE,GDP per capita (current US$),NY.GDP.PCAP.CD,278.813699,280.828951,276.688781,277.479715,281.558440,293.308854,277.233872,...,1093.654002,1304.969802,1430.000818,1434.899340,1445.071062,1464.583529,1548.170056,1683.740577,1463.985910,NaN

In [10]:
data.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Unnamed: 64
0,Aruba,ABW,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,24985.993281,24713.698045,26189.435509,26647.938101,27980.880695,28281.350482,29007.693003,NaN,NaN,NaN
1,Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,59.773194,59.860874,58.458015,78.706388,82.095231,101.108305,...,591.162759,641.871479,637.165523,613.856689,578.466353,547.228110,556.302002,524.162881,502.115487,NaN
2,Angola,AGO,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,4615.468028,5100.095808,5254.882338,5408.410496,4166.979684,3506.072885,4095.812942,3289.646664,2973.591160,NaN
3,Albania,ALB,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,4437.142885,4247.629984,4413.060861,4578.631994,3952.801215,4124.055726,4531.020806,5284.380184,5352.857411,NaN
4,Andorra,AND,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,43335.328862,38686.461264,39538.766722,41303.929371,35762.523074,37474.665406,38962.880354,41793.055258,40886.391165,NaN

In [11]:
data.set_index("Country Name", inplace=True)

In [12]:
data.head()

,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Unnamed: 64
Country Name,,,,,,,,,,,,,,,,,,,,,
Aruba,ABW,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24985.993281,24713.698045,26189.435509,26647.938101,27980.880695,28281.350482,29007.693003,NaN,NaN,NaN
Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,59.773194,59.860874,58.458015,78.706388,82.095231,101.108305,137.594352,...,591.162759,641.871479,637.165523,613.856689,578.466353,547.228110,556.302002,524.162881,502.115487,NaN
Angola,AGO,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4615.468028,5100.095808,5254.882338,5408.410496,4166.979684,3506.072885,4095.812942,3289.646664,2973.591160,NaN
Albania,ALB,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4437.142885,4247.629984,4413.060861,4578.631994,3952.801215,4124.055726,4531.020806,5284.380184,5352.857411,NaN
Andorra,AND,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,43335.328862,38686.461264,39538.766722,41303.929371,35762.523074,37474.665406,38962.880354,41793.055258,40886.391165,NaN

In [ ]:
#check again top-five rows of the dataframe
data.

### How to delete a column?

In [13]:
#Â delete Country Code, Indicator Name and Indicator Code columns
data.drop(columns=["Country Code","Indicator Name","Indicator Code"],inplace=True)

In [14]:
# check the dataframe
data.head()

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Unnamed: 64
Country Name,,,,,,,,,,,,,,,,,,,,,
Aruba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24985.993281,24713.698045,26189.435509,26647.938101,27980.880695,28281.350482,29007.693003,NaN,NaN,NaN
Afghanistan,59.773194,59.860874,58.458015,78.706388,82.095231,101.108305,137.594352,160.898589,129.108323,129.329713,...,591.162759,641.871479,637.165523,613.856689,578.466353,547.228110,556.302002,524.162881,502.115487,NaN
Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4615.468028,5100.095808,5254.882338,5408.410496,4166.979684,3506.072885,4095.812942,3289.646664,2973.591160,NaN
Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4437.142885,4247.629984,4413.060861,4578.631994,3952.801215,4124.055726,4531.020806,5284.380184,5352.857411,NaN
Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,43335.328862,38686.461264,39538.766722,41303.929371,35762.523074,37474.665406,38962.880354,41793.055258,40886.391165,NaN

### get data for Italy

In [15]:
italy=data.loc["Italy"]

In [16]:
type(italy)

pandas.core.series.Series

In [17]:
# get italy's gdp per capita for 2019
italy

1960             804.492623
1961             887.336745
1962             990.260152
1963            1126.019337
1964            1222.544540
1965            1304.453817
1966            1402.442354
1967            1533.692877
1968            1651.939377
1969            1813.388126
1970            2106.863953
1971            2305.609774
1972            2671.137308
1973            3205.252065
1974            3621.145839
1975            4106.993857
1976            4033.099367
1977            4603.599693
1978            5610.498107
1979            6990.285794
1980            8456.918982
1981            7622.833328
1982            7556.523429
1983            7832.575389
1984            7739.715280
1985            7990.686562
1986           11315.015165
1987           14234.728649
1988           15744.661271
1989           16386.662217
                   ...
1991           21956.529760
1992           23243.474542
1993           18738.763903
1994           19337.630906
1995           20664.552270
1996           23081.604676
1997           21829.345823
1998           22318.137301
1999           21997.624316
2000           20087.591986
2001           20483.215995
2002           22270.144123
2003           27465.675299
2004           31259.716495
2005           32043.140368
2006           33501.658167
2007           37822.665238
2008           40778.342737
2009           37079.758670
2010           36000.520118
2011           38599.062207
2012           35053.526244
2013           35549.974697
2014           35518.415292
2015           30230.226302
2016           30939.714246
2017           32406.720315
2018           34520.085162
2019           33189.565799
Unnamed: 64             NaN
Name: Italy, Length: 61, dtype: float64

In [18]:
italy.tail()

2016           30939.714246
2017           32406.720315
2018           34520.085162
2019           33189.565799
Unnamed: 64             NaN
Name: Italy, dtype: float64

### Find the year that italy has the highest increase of gdb per capita

- Calculate the yearly percentage increase compared to previous year 
- find the year that has highest increase in terms of percentage.

calculate the yearly change in percentage

In [19]:
italy_pct_change=italy.pct_change()

In [20]:
italy_pct_change

1960                NaN
1961           0.102977
1962           0.115991
1963           0.137094
1964           0.085723
1965           0.066999
1966           0.075118
1967           0.093587
1968           0.077099
1969           0.097733
1970           0.161838
1971           0.094333
1972           0.158538
1973           0.199958
1974           0.129754
1975           0.134170
1976          -0.017992
1977           0.141455
1978           0.218720
1979           0.245930
1980           0.209810
1981          -0.098628
1982          -0.008699
1983           0.036532
1984          -0.011856
1985           0.032426
1986           0.416025
1987           0.258039
1988           0.106074
1989           0.040776
                 ...
1991           0.054295
1992           0.058613
1993          -0.193805
1994           0.031959
1995           0.068619
1996           0.116966
1997          -0.054254
1998           0.022391
1999          -0.014361
2000          -0.086829
2001           0.019695
2002           0.087239
2003           0.233296
2004           0.138138
2005           0.025062
2006           0.045517
2007           0.128979
2008           0.078146
2009          -0.090700
2010          -0.029106
2011           0.072181
2012          -0.091855
2013           0.014163
2014          -0.000888
2015          -0.148886
2016           0.023469
2017           0.047415
2018           0.065214
2019          -0.038543
Unnamed: 64         NaN
Name: Italy, Length: 61, dtype: float64

In [21]:
# multiply italy_pct_change by 100
italy_pct_change=italy_pct_change*100

In [22]:
italy_pct_change

1960                 NaN
1961           10.297686
1962           11.599137
1963           13.709446
1964            8.572251
1965            6.699901
1966            7.511844
1967            9.358711
1968            7.709920
1969            9.773285
1970           16.183840
1971            9.433254
1972           15.853834
1973           19.995781
1974           12.975384
1975           13.416969
1976           -1.799235
1977           14.145457
1978           21.871980
1979           24.592962
1980           20.981019
1981           -9.862760
1982           -0.869885
1983            3.653161
1984           -1.185563
1985            3.242642
1986           41.602540
1987           25.803885
1988           10.607386
1989            4.077579
                 ...
1991            5.429546
1992            5.861331
1993          -19.380539
1994            3.195873
1995            6.861861
1996           11.696612
1997           -5.425354
1998            2.239149
1999           -1.436110
2000           -8.682903
2001            1.969494
2002            8.723865
2003           23.329580
2004           13.813755
2005            2.506177
2006            4.551732
2007           12.897890
2008            7.814567
2009           -9.069972
2010           -2.910587
2011            7.218068
2012           -9.185549
2013            1.416258
2014           -0.088775
2015          -14.888584
2016            2.346949
2017            4.741498
2018            6.521378
2019           -3.854334
Unnamed: 64          NaN
Name: Italy, Length: 61, dtype: float64

find the year that has highest change

In [23]:
italy_pct_change.idxmax()

'1986'

### Find the years that GDP per capita decreased compared to the previous year.

In [24]:
italy_pct_change

1960                 NaN
1961           10.297686
1962           11.599137
1963           13.709446
1964            8.572251
1965            6.699901
1966            7.511844
1967            9.358711
1968            7.709920
1969            9.773285
1970           16.183840
1971            9.433254
1972           15.853834
1973           19.995781
1974           12.975384
1975           13.416969
1976           -1.799235
1977           14.145457
1978           21.871980
1979           24.592962
1980           20.981019
1981           -9.862760
1982           -0.869885
1983            3.653161
1984           -1.185563
1985            3.242642
1986           41.602540
1987           25.803885
1988           10.607386
1989            4.077579
                 ...
1991            5.429546
1992            5.861331
1993          -19.380539
1994            3.195873
1995            6.861861
1996           11.696612
1997           -5.425354
1998            2.239149
1999           -1.436110
2000           -8.682903
2001            1.969494
2002            8.723865
2003           23.329580
2004           13.813755
2005            2.506177
2006            4.551732
2007           12.897890
2008            7.814567
2009           -9.069972
2010           -2.910587
2011            7.218068
2012           -9.185549
2013            1.416258
2014           -0.088775
2015          -14.888584
2016            2.346949
2017            4.741498
2018            6.521378
2019           -3.854334
Unnamed: 64          NaN
Name: Italy, Length: 61, dtype: float64

In [29]:
italy_pct_change < 0

1960           False
1961           False
1962           False
1963           False
1964           False
1965           False
1966           False
1967           False
1968           False
1969           False
1970           False
1971           False
1972           False
1973           False
1974           False
1975           False
1976            True
1977           False
1978           False
1979           False
1980           False
1981            True
1982            True
1983           False
1984            True
1985           False
1986           False
1987           False
1988           False
1989           False
               ...
1991           False
1992           False
1993            True
1994           False
1995           False
1996           False
1997            True
1998           False
1999            True
2000            True
2001           False
2002           False
2003           False
2004           False
2005           False
2006           False
2007           False
2008           False
2009            True
2010            True
2011           False
2012            True
2013           False
2014            True
2015            True
2016           False
2017           False
2018           False
2019            True
Unnamed: 64    False
Name: Italy, Length: 61, dtype: bool

In [25]:
italy_pct_change[italy_pct_change < 0]

1976    -1.799235
1981    -9.862760
1982    -0.869885
1984    -1.185563
1993   -19.380539
1997    -5.425354
1999    -1.436110
2000    -8.682903
2009    -9.069972
2010    -2.910587
2012    -9.185549
2014    -0.088775
2015   -14.888584
2019    -3.854334
Name: Italy, dtype: float64

In [26]:
italy_negative=italy_pct_change[italy_pct_change < 0]

In [27]:
italy_negative

1976    -1.799235
1981    -9.862760
1982    -0.869885
1984    -1.185563
1993   -19.380539
1997    -5.425354
1999    -1.436110
2000    -8.682903
2009    -9.069972
2010    -2.910587
2012    -9.185549
2014    -0.088775
2015   -14.888584
2019    -3.854334
Name: Italy, dtype: float64

In [28]:
# get only years
italy_negative.index

Index(['1976', '1981', '1982', '1984', '1993', '1997', '1999', '2000', '2009',
       '2010', '2012', '2014', '2015', '2019'],
      dtype='object')

## Find the year that GDP per capita of the world increased the most compared to previous year

In [ ]:
data.head()

In [30]:
# first get the data for world
#Â there is an index named World
world=data.loc["World"]

In [31]:
#Â now find the year that has highest increase in percentange
world

1960             452.108859
1961             464.049009
1962             489.547101
1963             516.615106
1964             554.553301
1965             591.718115
1966             628.738759
1967             655.873528
1968             693.901057
1969             749.725142
1970             803.946597
1971             870.437316
1972             984.529368
1973            1178.088885
1974            1332.802790
1975            1457.154424
1976            1556.815365
1977            1729.526272
1978            2005.108692
1979            2288.666044
1980            2532.763188
1981            2576.688007
1982            2507.321433
1983            2513.128165
1984            2560.998290
1985            2643.758402
1986            3069.913093
1987            3431.580688
1988            3772.401359
1989            3870.413005
                   ...
1991            4464.654312
1992            4668.240469
1993            4669.581597
1994            4939.834904
1995            5412.344059
1996            5453.312839
1997            5357.069165
1998            5272.633304
1999            5395.942835
2000            5498.329705
2001            5396.891939
2002            5533.425294
2003            6131.223225
2004            6820.615196
2005            7297.153399
2006            7811.936206
2007            8694.900257
2008            9423.757252
2009            8830.306909
2010            9551.335653
2011           10488.334016
2012           10605.208322
2013           10781.855305
2014           10952.344419
2015           10246.507362
2016           10281.908800
2017           10817.481947
2018           11381.680597
2019           11435.609873
Unnamed: 64             NaN
Name: World, Length: 61, dtype: float64

In [36]:
world_pct_change = world.pct_change() * 100

In [37]:
world_pct_change

1960                 NaN
1961            2.640990
1962            5.494698
1963            5.529193
1964            7.343609
1965            6.701757
1966            6.256466
1967            4.315746
1968            5.797997
1969            8.044963
1970            7.232178
1971            8.270539
1972           13.107440
1973           19.660106
1974           13.132617
1975            9.330085
1976            6.839422
1977           11.093859
1978           15.933983
1979           14.141745
1980           10.665477
1981            1.734265
1982           -2.692083
1983            0.231591
1984            1.904802
1985            3.231557
1986           16.119275
1987           11.781037
1988            9.931886
1989            2.598123
                 ...
1991            4.186912
1992            4.559953
1993            0.028729
1994            5.787527
1995            9.565282
1996            0.756951
1997           -1.764866
1998           -1.576158
1999            2.338671
2000            1.897479
2001           -1.844883
2002            2.529852
2003           10.803398
2004           11.243955
2005            6.986733
2006            7.054570
2007           11.302756
2008            8.382580
2009           -6.297386
2010            8.165387
2011            9.810129
2012            1.114327
2013            1.665663
2014            1.581260
2015           -6.444621
2016            0.345498
2017            5.208888
2018            5.215619
2019            0.473825
Unnamed: 64          NaN
Name: World, Length: 61, dtype: float64

In [38]:
world_pct_change.idxmax()

'1973'

## find top 10 years that have highest standart deviation

In [41]:
data.head()

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Unnamed: 64
Country Name,,,,,,,,,,,,,,,,,,,,,
Aruba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24985.993281,24713.698045,26189.435509,26647.938101,27980.880695,28281.350482,29007.693003,NaN,NaN,NaN
Afghanistan,59.773194,59.860874,58.458015,78.706388,82.095231,101.108305,137.594352,160.898589,129.108323,129.329713,...,591.162759,641.871479,637.165523,613.856689,578.466353,547.228110,556.302002,524.162881,502.115487,NaN
Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4615.468028,5100.095808,5254.882338,5408.410496,4166.979684,3506.072885,4095.812942,3289.646664,2973.591160,NaN
Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4437.142885,4247.629984,4413.060861,4578.631994,3952.801215,4124.055726,4531.020806,5284.380184,5352.857411,NaN
Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,43335.328862,38686.461264,39538.766722,41303.929371,35762.523074,37474.665406,38962.880354,41793.055258,40886.391165,NaN

In [46]:
#Â first calculate standart deviation for each year
data_std=data.std(axis="index")

In [47]:
data_std

1960             616.785920
1961             640.565654
1962             671.604311
1963             711.308655
1964             777.885298
1965             871.592933
1966             941.155061
1967             972.379823
1968            1003.955689
1969            1081.005839
1970            1502.515921
1971            1667.576421
1972            1972.996423
1973            2484.508375
1974            3078.850036
1975            3901.760053
1976            4239.908374
1977            4629.686988
1978            5106.088257
1979            6110.719389
1980            7027.306246
1981            6588.758320
1982            6020.992290
1983            5587.148107
1984            5427.941516
1985            5415.922307
1986            6553.874383
1987            7829.097029
1988            8476.585531
1989            8597.477810
                   ...
1991           10090.729157
1992           10836.770255
1993           10297.909518
1994           10990.545497
1995           12492.832646
1996           12660.875855
1997           11897.722518
1998           12311.413958
1999           12817.233596
2000           12312.902898
2001           12297.298688
2002           13157.912758
2003           15225.571063
2004           17193.978510
2005           18117.241341
2006           19972.556260
2007           22922.308837
2008           24399.207273
2009           21341.053469
2010           21914.651799
2011           24139.100126
2012           23348.430334
2013           24931.331730
2014           25326.276983
2015           22689.486513
2016           22890.224017
2017           23746.968589
2018           22823.287773
2019           19337.616848
Unnamed: 64             NaN
Length: 61, dtype: float64

In [48]:
#Â now top-10 years having the hightest standart deviation
data_std.nlargest(10)

2014    25326.276983
2013    24931.331730
2008    24399.207273
2011    24139.100126
2017    23746.968589
2012    23348.430334
2007    22922.308837
2016    22890.224017
2018    22823.287773
2015    22689.486513
dtype: float64

### Which country has the highest gdp_per_capita in 2019?

In [ ]:
data.head()

In [ ]:
#Â get the data for the year 2019
data_2019=data

In [ ]:
data_2019

In [ ]:
# now get the country
data_2019.

# Rank of Luxembourg

find the rank of Luxembourg each year

In [ ]:
# calculate the rank of each country for each year
data_rank=data.

In [ ]:
data_rank

In [ ]:
#Â now get the rank of Luxembourg
lux_rank=data_rank.

In [ ]:
# plot the rank of luxembourg
lux_rank.

In [ ]:
# print the years where Luxembourg ranks top
lux_rank